// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Syndic.Api.Infrastructure.Persistence;

#nullable disable

namespace Syndic.Api.Migrations;

[DbContext(typeof(SyndicDbContext))]
[Migration("20260620000000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("ClaimType").HasColumnType("text");
            b.Property<string>("ClaimValue").HasColumnType("text");
            b.Property<Guid>("RoleId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("RoleId");
            b.ToTable("AspNetRoleClaims");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("ClaimType").HasColumnType("text");
            b.Property<string>("ClaimValue").HasColumnType("text");
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("UserId");
            b.ToTable("AspNetUserClaims");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
        {
            b.Property<string>("LoginProvider").HasColumnType("text");
            b.Property<string>("ProviderKey").HasColumnType("text");
            b.Property<string>("ProviderDisplayName").HasColumnType("text");
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.HasKey("LoginProvider", "ProviderKey");
            b.HasIndex("UserId");
            b.ToTable("AspNetUserLogins");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
        {
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.Property<Guid>("RoleId").HasColumnType("uuid");
            b.HasKey("UserId", "RoleId");
            b.HasIndex("RoleId");
            b.ToTable("AspNetUserRoles");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
        {
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.Property<string>("LoginProvider").HasColumnType("text");
            b.Property<string>("Name").HasColumnType("text");
            b.Property<string>("Value").HasColumnType("text");
            b.HasKey("UserId", "LoginProvider", "Name");
            b.ToTable("AspNetUserTokens");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
            b.Property<string>("Name").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("character varying(256)");
            b.HasKey("Id");
            b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex");
            b.ToTable("AspNetRoles");
        });

        modelBuilder.Entity("Syndic.Modules.Identity.Domain.Entities.ApplicationUser", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<int>("AccessFailedCount").HasColumnType("integer");
            b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
            b.Property<string>("Email").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<bool>("EmailConfirmed").HasColumnType("boolean");
            b.Property<bool>("LockoutEnabled").HasColumnType("boolean");
            b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("timestamp with time zone");
            b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("PasswordHash").HasColumnType("text");
            b.Property<string>("PhoneNumber").HasColumnType("text");
            b.Property<bool>("PhoneNumberConfirmed").HasColumnType("boolean");
            b.Property<string>("RefreshToken").HasColumnType("text");
            b.Property<DateTimeOffset?>("RefreshTokenExpiresAt").HasColumnType("timestamp with time zone");
            b.Property<Guid?>("ResidentId").HasColumnType("uuid");
            b.Property<string>("SecurityStamp").HasColumnType("text");
            b.Property<bool>("TwoFactorEnabled").HasColumnType("boolean");
            b.Property<string>("UserName").HasMaxLength(256).HasColumnType("character varying(256)");
            b.HasKey("Id");
            b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
            b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex");
            b.ToTable("AspNetUsers");
        });

        modelBuilder.Entity("Syndic.Modules.Copropriete.Domain.Entities.Residence", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            b.Property<string>("Address").IsRequired().HasColumnName("adresse").HasColumnType("text");
            b.Property<string>("City").IsRequired().HasMaxLength(100).HasColumnName("ville").HasColumnType("character varying(100)");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnName("nom").HasColumnType("character varying(200)");
            b.Property<DateTimeOffset?>("UpdatedAt").HasColumnName("updated_at").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.ToTable("residences");
        });

        modelBuilder.Entity("Syndic.Modules.Copropriete.Domain.Entities.GroupeHabitation", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnName("nom").HasColumnType("character varying(200)");
            b.Property<Guid>("ResidenceId").HasColumnName("residence_id").HasColumnType("uuid");
            b.Property<DateTimeOffset?>("UpdatedAt").HasColumnName("updated_at").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("ResidenceId").HasDatabaseName("ix_groupes_habitation_residence_id");
            b.ToTable("groupes_habitation");
        });

        modelBuilder.Entity("Syndic.Modules.Copropriete.Domain.Entities.Immeuble", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            b.Property<string>("Address").HasColumnName("adresse").HasColumnType("text");
            b.Property<string>("BlockName").IsRequired().HasMaxLength(100).HasColumnName("nom_bloc").HasColumnType("character varying(100)");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
            b.Property<Guid>("GroupeHabitationId").HasColumnName("groupe_habitation_id").HasColumnType("uuid");
            b.Property<int>("NbFloors").HasColumnName("nb_etages").HasColumnType("integer");
            b.Property<DateTimeOffset?>("UpdatedAt").HasColumnName("updated_at").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("GroupeHabitationId").HasDatabaseName("ix_immeubles_groupe_habitation_id");
            b.ToTable("immeubles");
        });

        modelBuilder.Entity("Syndic.Modules.Copropriete.Domain.Entities.Lot", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            b.Property<decimal?>("Area").HasColumnName("superficie").HasColumnType("numeric(10,2)");
            b.Property<decimal>("Balance").HasColumnName("solde").HasColumnType("numeric(14,2)");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
            b.Property<int>("Floor").HasColumnName("etage").HasColumnType("integer");
            b.Property<Guid>("ImmeubleId").HasColumnName("immeuble_id").HasColumnType("uuid");
            b.Property<string>("Number").IsRequired().HasMaxLength(50).HasColumnName("numero").HasColumnType("character varying(50)");
            b.Property<string>("Type").IsRequired().HasMaxLength(30).HasColumnName("type").HasColumnType("character varying(30)");
            b.Property<DateTimeOffset?>("UpdatedAt").HasColumnName("updated_at").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("ImmeubleId").HasDatabaseName("ix_lots_immeuble_id");
            b.ToTable("lots");
        });

        modelBuilder.Entity("Syndic.Modules.Copropriete.Domain.Entities.Resident", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            b.Property<bool>("IsAccountActivated").HasColumnName("compte_active").HasColumnType("boolean");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
            b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnName("email").HasColumnType("character varying(256)");
            b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnName("prenom").HasColumnType("character varying(100)");
            b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnName("nom").HasColumnType("character varying(100)");
            b.Property<string>("Phone").HasMaxLength(30).HasColumnName("telephone").HasColumnType("character varying(30)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnName("statut").HasColumnType("character varying(20)");
            b.Property<string>("Type").IsRequired().HasMaxLength(20).HasColumnName("type").HasColumnType("character varying(20)");
            b.Property<DateTimeOffset?>("UpdatedAt").HasColumnName("updated_at").HasColumnType("timestamp with time zone");
            b.Property<Guid?>("UserId").HasColumnName("user_id").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("Email").IsUnique().HasDatabaseName("ix_residents_email");
            b.HasIndex("UserId").IsUnique().HasDatabaseName("ix_residents_user_id").HasFilter("user_id IS NOT NULL");
            b.ToTable("residents");
        });

        modelBuilder.Entity("Syndic.Modules.Copropriete.Domain.Entities.LotResident", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
            b.Property<DateOnly>("StartDate").HasColumnName("date_debut").HasColumnType("date");
            b.Property<DateOnly?>("EndDate").HasColumnName("date_fin").HasColumnType("date");
            b.Property<Guid>("LotId").HasColumnName("lot_id").HasColumnType("uuid");
            b.Property<Guid>("ResidentId").HasColumnName("resident_id").HasColumnType("uuid");
            b.Property<string>("Type").IsRequired().HasMaxLength(20).HasColumnName("type").HasColumnType("character varying(20)");
            b.Property<DateTimeOffset?>("UpdatedAt").HasColumnName("updated_at").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("LotId").HasDatabaseName("ix_lot_residents_lot_id");
            b.HasIndex("ResidentId").HasDatabaseName("ix_lot_residents_resident_id");
            b.ToTable("lot_residents");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
        {
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                .WithMany()
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
        {
            b.HasOne("Syndic.Modules.Identity.Domain.Entities.ApplicationUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
        {
            b.HasOne("Syndic.Modules.Identity.Domain.Entities.ApplicationUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
        {
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                .WithMany()
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.HasOne("Syndic.Modules.Identity.Domain.Entities.ApplicationUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
        {
            b.HasOne("Syndic.Modules.Identity.Domain.Entities.ApplicationUser", null)
                .WithMany()
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("Syndic.Modules.Copropriete.Domain.Entities.GroupeHabitation", b =>
        {
            b.HasOne("Syndic.Modules.Copropriete.Domain.Entities.Residence", "Residence")
                .WithMany("GroupesHabitation")
                .HasForeignKey("ResidenceId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Residence");
        });

        modelBuilder.Entity("Syndic.Modules.Copropriete.Domain.Entities.Immeuble", b =>
        {
            b.HasOne("Syndic.Modules.Copropriete.Domain.Entities.GroupeHabitation", "GroupeHabitation")
                .WithMany("Immeubles")
                .HasForeignKey("GroupeHabitationId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("GroupeHabitation");
        });

        modelBuilder.Entity("Syndic.Modules.Copropriete.Domain.Entities.Lot", b =>
        {
            b.HasOne("Syndic.Modules.Copropriete.Domain.Entities.Immeuble", "Immeuble")
                .WithMany("Lots")
                .HasForeignKey("ImmeubleId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.Navigation("Immeuble");
        });

        modelBuilder.Entity("Syndic.Modules.Copropriete.Domain.Entities.LotResident", b =>
        {
            b.HasOne("Syndic.Modules.Copropriete.Domain.Entities.Lot", "Lot")
                .WithMany("LotResidents")
                .HasForeignKey("LotId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.HasOne("Syndic.Modules.Copropriete.Domain.Entities.Resident", "Resident")
                .WithMany("LotResidents")
                .HasForeignKey("ResidentId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
            b.Navigation("Lot");
            b.Navigation("Resident");
        });

        modelBuilder.Entity("Syndic.Modules.Copropriete.Domain.Entities.GroupeHabitation", b =>
        {
            b.Navigation("Immeubles");
        });
        modelBuilder.Entity("Syndic.Modules.Copropriete.Domain.Entities.Immeuble", b =>
        {
            b.Navigation("Lots");
        });
        modelBuilder.Entity("Syndic.Modules.Copropriete.Domain.Entities.Lot", b =>
        {
            b.Navigation("LotResidents");
        });
        modelBuilder.Entity("Syndic.Modules.Copropriete.Domain.Entities.Residence", b =>
        {
            b.Navigation("GroupesHabitation");
        });
        modelBuilder.Entity("Syndic.Modules.Copropriete.Domain.Entities.Resident", b =>
        {
            b.Navigation("LotResidents");
        });
#pragma warning restore 612, 618
    }
}
